### ISSUE TITLE
missing git tags

### ISSUE THREAD

**Issue by anthraxx** [whitequark/python-itanium_demangler#19]
I'd like to very kindly ask you to always push git tags on release. Specifically it would be nice if you can tag and push 1.0 according to what has been released at pypi.

Reasoning:
It's not just important that it is easy to map tags to actual releases in
the source tree. But for distro packaging we actually require to have a
matching git tag for every release as the rule of thumb is to build from
the version control state in order to aid transparency and confidence in
public reviewed code etc.

Problem:
As of the above, the missing tag for 1.0 create the issue for me that i
can't package this library for our Distro currently.

Thank you so much :cat:

**Comment by whitequark** [comment]
Done. Also pushed a v1.1 release on PyPI and in the repo.

**Comment by anthraxx** [comment]
Super quick, thank you! :cat2:
