### ISSUE TITLE
Incorrect Substitution Handling

### ISSUE THREAD

**Issue by CraftSpider** [whitequark/python-itanium_demangler#2]
When demangling certain symbols, the substitution isn't handled correctly. An example from libc++ is `_ZStplIcSt11char_traitsIcESaIcEESbIT_T0_T1_ES3_RKS6_`, which should demangle to `std::basic_string<char, std::char_traits<char>, std::allocator<char>> std::operator+<char, std::char_traits<char>, std::allocator<char>>(char, std::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)` This seems to be due to the demangler including operator templates in the substitution, as they should be excluded despite being template overloads due to the substitution rule that all operator names are not valid for substitution

**Comment by CraftSpider** [comment]
Sorry for the original blank issue, hit ctrl+enter by accident

**Comment by whitequark** [comment]
Do you think you could write a PR?

**Comment by CraftSpider** [comment]
Probably can get one in by tomorrow

**Comment by CraftSpider** [comment]
As a quick note from experimentation: `operator_` is inserted into the substitution table as a template name, but `operator_<...>` is not
