### ISSUE TITLE
RFC: Function Qualifiers

### ISSUE THREAD

**Issue by CraftSpider** [whitequark/python-itanium_demangler#9]
Currently, qualifiers on a function are blindly places to the right of the function, which isn't a valid placement. As an example:
`_Z1fPFvvE` demangles to `f(void ()*)` instead of `f(void (*)())`
I'm opening this as an issue, as I'm not sure the cleanest way to handle stringifying qualifiers for functions correctly.

**Comment by whitequark** [comment]
Yeah that's super unfortunate, and I remember seeing this issue and postponing it. I think you basically have to special-case that *somewhere*.

**Comment by CraftSpider** [comment]
My one idea is to have nodes support a `_left` and `_right` function, as a couple will need this functionality (Functions, Arrays, and Member Functions will have to use a function left and provide their own left), and the qualifier can use that to get 'what goes on the left' and 'what goes on the right'. If we want to minimize if cases, the default node just returns the whole type for `_left` and nothing for `_right`

**Comment by whitequark** [comment]
Yeah, I've read the code, I don't quite understand the design intent. What are "left" and "right" here? LHS and RHS? What happens if a node can't appear on LHS?

**Comment by CraftSpider** [comment]
In this case, `left` and `right` are purely for stringifying. They represent 'stuff to the left of a potential qualifier' (EG `void (` or `int`) and 'stuff to the right of a potential qualifier' (EG `)(int)`, or nothing). While some things could not be qualified ever in reality, putting it on everything means there doesn't need to be an awkward `isinstance` or `hasattr` check. A node will never be 'unable' to appear on left or right, as language limitations on where a type may appear aren't relevant (The parser will return None for invalid encodings, not generate a crazy string like `<int>*`)

**Comment by whitequark** [comment]
I feel like there might be a nicer solution, but done is better than perfect, so, merged.
